# The docker compose version is first defined
version: "3.0"

services:
  frontend:
    # Point to the frontend directory to build from.
    build: frontend
    # Map the port for the frontend for nginx.
    ports:
      - "80:80"

  backend:
    # Point to the backend directory to build from.
    build: backend
    # Expose and link the port for the backend.
    ports:
      - "3000:3000"
    # Link the backend to the database container which will
    # allow the backend to connect to the database.
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
